name = "my-trello-back"
compatibility_date = "2021-11-17"
main = "./dist/index.mjs"
# required for new wrangler to not perform own building which works but no sourcemaps...
no_bundle = true

required_secrets=["ACCESS_TOKEN_SECRET", "REFRESH_TOKEN_SECRET", "REDIS_TOKEN", "SENTRY_DNS"]

[env.kowospace]
# 'unbound' is EXPENSIVE!! 'bundled' is cheap
usage_model = "bundled"
kv_namespaces = [
         { binding = "KV", id = "60254b117a9d40d2be797d802eb4182a", preview_id = "d83c5d26f8544935886027655cf2f6af" }
]

routes = ["my-trello-back.kowo.space/*"]

[env.myworkersdev]
# override name for beautiful domain, otherwise will be "name-envname"
name="my-trello-back"
workers_dev = true
kv_namespaces = []

[build]
command = "$deploymode && { [ -z $NPMINSTALL ] || npm install && npm run build; exit $? ; } || echo '...build disabled...'"

[dev]
port = 6422